#import "global_format.typ"

#let doc = global_format.init.with("Analysis of INDOPACOMS's Key Adversarial Challenges", "Maj Matthew Howard", "Air, Space, and Joint Warfare (AIR-603A)")
#show: doc

Global Integrated Intelligence, Surveillance, and Reconnaissance, together with Joint Intelligence, underpins combat power in the Indo-Pacific because it creates decision advantage. Admiral Paparo’s challenge of China’s anti-access and area denial system, enabled by counterspace and counter-ISR capabilities, directly threatens ISR and Joint Intelligence. Agile combat employment can mitigate those effects specifically by preserving ISR generation, ISR data flow, and forward intelligence support.

Global ISR is the foundation upon which every joint, interagency, and coalition operation achieves success. It is a core element of modern operations rather than a secondary support activity. Joint Doctrine defines ISR as the “coordinated and integrated acquisition, processing and provision of timely, accurate, relevant, coherent and assured information and intelligence to support commanders’ conduct of activities,” (JP 2-0) which captures the Global Integrated ISR function’s focus on turning multi‑domain data into usable intelligence for planners and operators. Essentially, Global Integrated ISR synchronizes sensors, platforms, processing, exploitation, and dissemination so that commanders at all echelons can anticipate threats and act faster than an adversary (AFDP 3-0).

The joint function of Intelligence is as defined in JP 3‑0 exists to help commanders understand the operational environment, identify centers of gravity, and support planning and execution. Odom and Hayes argue that effective joint operations require “a comprehensive cross‑domain view of the adversary and the environment,” and that intelligence must integrate contributions across domains to reveal vulnerabilities and inform joint force design @odom. In practice, Global Integrated ISR is focused on providing much of the collection and some analysis, while Joint Intelligence defines requirements, fuses inputs from all sources, and disseminates actionable understanding.

In his 2025 statement, Admiral Paparo identifies the People’s Republic of China as “the pacing challenge” and describes an “advanced, multi‑layered A2AD network” designed to hold US and allied forces at risk across the first and second island chains @paparo. He notes that China fields large inventories of precision ballistic and cruise missiles capable of striking forward air and naval bases. It also integrates those weapons with sophisticated air and maritime defenses to constrain US freedom of maneuver @paparo. This missile complex threatens the airfields, logistics hubs, and command nodes that Global Integrated ISR relies on to deploy sensors and disseminate intelligence.

Paparo also highlights China’s expanding space and counterspace capabilities, warning that Beijing is investing in “space‑based ISR, counterspace systems, and cyber tools” to degrade US command, control, and ISR and “paralyze our decision cycles” @paparo. Swope’s Space Threat Assessment concludes that China has demonstrated multiple counterspace capabilities, including jamming, spoofing, and anti‑satellite weapons. PLA units train to evade foreign ISR satellites by rapidly hiding equipment and maintaining radio silence when they pass overhead @swope. Together, this A2AD and counter‑ISR posture forms an adversarial challenge for Global Integrated ISR and Joint Intelligence.

First, A2AD reduces ISR access and persistence by threatening bases and airspace. If forward airfields are within range of large missile salvos, ISR aircraft may have to operate from fewer, more distant locations. This shrinks dwell time over critical areas and creates gaps in coverage @paparo. Reduced access and persistence directly diminish the “coordinated and integrated acquisition” of information that joint doctrine associates with ISR (JP 2-0).

Second, counterspace and electronic attack disrupt the ISR network and the data‑to‑decision cycle. Paparo calls for “resilient, proliferated space architectures” because he anticipates attacks on US space‑based communications and ISR systems @paparo. Swope highlights instances of GPS and SATCOM jamming in the Indo‑Pacific. Additionally, Swope warns that China is likely seeking ways to hold satellite constellations at risk because of the advantages they provide @swope. If ISR data cannot reliably flow through space, the joint intelligence cycle slows or fractures.

Third, these pressures make it harder for Joint Intelligence to build the cross‑domain picture as Odom and Hayes describe. When ISR platforms are constrained by A2AD, space systems are contested, and communications are degraded, the joint force’s ability to integrate information from multiple domains into a coherent view of the adversary declines @odom. That undercuts Paparo’s goal of maintaining decision advantage and timely, accurate warning.

Agile combat employment is designed to address the vulnerabilities that A2AD and counter‑ISR exploit. AFDN 1‑21 defines ACE as “a proactive and reactive operational scheme of maneuver executed within threat timelines to increase resiliency and survivability while generating combat power.” It states that “Intelligence and CI should be prepared to support operations in a CDO-L environment characterized by mission command and rapidly changing basing. As operations evolve, real time communications feedback with warfighters and the Intelligence Community agile and resilient” (AFDN 1-12). That doctrinal guidance directly connects ACE’s posture and maneuver to Global Integrated ISR and Joint Intelligence.

ACE’s posture and maneuver preserve ISR sortie generation, which is the baseline for Global Integrated ISR. By operating ISR platforms from multiple smaller or austere locations instead of a few large hubs, ACE makes it harder for China’s missiles to suppress ISR in a single strike. This ensures that aircraft can still launch, recover, and maintain collection in support of the joint intelligence process (AFDN 1-12). In doctrinal terms, this protects the “collection” part of ISR, the ability to keep sensors on‑station despite A2AD.

Furthermore, ACE deliberately distributes intelligence support to match dispersed operations. AFDN 1-12 states that “support to expeditionary mission generation units and the contingency intelligence network will further enable the ability to achieve desired airpower effects.” Also, that intelligence must “adapt and evolve to meet dynamic C2 requirements” as units move. Practically, this means pushing modular communications and processing capability out to the field. By doing so, ACE enables forward locations to produce time‑sensitive intelligence, and feed mission reports back into the theater enterprise. This approach keeps the ISR processing and dissemination functions viable at the edge, even if major nodes are degraded.

Additionally, ACE is built to function with resilient communications, which directly supports ISR data flow needs. AFDN 1-12 lists “resilient communications to function in contested, degraded, or operationally limited environments” as a core requirement for ACE. It emphasizes that “mission report communications flow should be adapted for real time operations”. When combined with the resilient space architectures Paparo calls for, ACE’s ability to shift communications paths allows ISR data and intelligence products to continue flowing between sensors, analysts, and warfighters. Even under jamming or cyber-attack, ISR data flow can be maintained @paparo.

Finally, ACE leverages the second and third party alliances that Warner emphasizes as essential for Joint Intelligence and ISR in the Indo‑Pacific. Warner notes that “effective theater response doesn’t just happen” but comes from long‑term investment in relationships, exercises, and shared processes @warner. ACE incorporates allied and partner airfields into a distributed operating network. This expands ISR basing options, increases vantage points for collection, and deepens coalition intelligence sharing @warner.

Global Integrated ISR and the Joint Intelligence exist to provide decision advantage for the joint force. Admiral Paparo’s 2025 assessment shows that China’s A2AD, counterspace, and cyber capabilities are designed to deny access, and disrupt ISR networks @paparo. Air Force doctrine makes clear that agile combat employment is meant to keep ISR and intelligence effective in exactly this kind of contested environment. It preserves ISR sortie generation through dispersal, keeps ISR data flowing through resilient communications, and maintains forward intelligence support tied into contingency networks (AFDN 1-12). Combined with allied and partner basing and long‑term theater security cooperation, ACE functions as an operating concept that protects and enhances Global Integrated ISR and Joint Intelligence in a contested theater.

#pagebreak()

#bibliography("jw_assignment1.yml", full: true, style: "apa")
